In [3]:
from urllib.request import urlopen, Request
from bs4 import BeautifulSoup
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import pandas as pd
import matplotlib.pyplot as plt

finviz_url = 'https://finviz.com/quote.ashx?t='
tickers = ['AMZN','GOOG','META','AAPL','MSFT','NVDA','TSLA','PG','MCD','NKE']
parsed_data = []
news_tables = {}
for ticker in tickers:
    url = finviz_url + ticker

    req = Request(url=url, headers={'user-agent': 'my-app'})
    response = urlopen(req)
    date=[]
    html = BeautifulSoup(response, features='html.parser')
    news_table = html.find(id='news-table')
    news_tables[ticker] = news_table
    data= news_table.findAll('tr')
    i=0
    for index,row in enumerate(data):
        if row.a:
            title = row.a.text
            date = row.td.text.split(' ')
        if len(date)==22:
            date1=date[12]
            if date1=='Today':
                date1='Jan-31-25'
            dt=date1
            time=date[13]
            time=time[:7]
        else:
            date1=dt
            time=date[12]
            time=time[:7]
        parsed_data.append([ticker, date1, time,title])
parsed_data
df = pd.DataFrame(parsed_data, columns=['ticker', 'date', 'time', 'title'])
df

,ticker,date,time,title
0,AMZN,Feb-19-25,07:56AM,Amazon joins forces with Memorial Sloan Ketter...
1,AMZN,Feb-19-25,06:38AM,Amazon $100B AI Investment Stumbles Amid Suppl...
2,AMZN,Feb-19-25,06:14AM,Can Oracle (ORCL) Capitalize on the $500B AI S...
3,AMZN,Feb-19-25,05:30AM,Better Artificial Intelligence Stock: Rigetti ...
4,AMZN,Feb-19-25,05:00AM,"Amazon, Disney, Starbucks and 5 other big comp..."
...,...,...,...,...
995,NKE,Jan-22-25,04:15PM,Gap CEO at Davos: We are not breaking up the c...
996,NKE,Jan-22-25,01:56PM,"Is NIKE, Inc. (NKE) the Best Stock to Invest I..."
997,NKE,Jan-22-25,12:15PM,"REI hires former Nike, Athleta exec as its new..."
998,NKE,Jan-22-25,07:45AM,"1 S&P 500 Stock to Buy With $1,000 in 2025 and..."
999,NKE,Jan-22-25,07:14AM,"REI taps Nike, Athleta vet Mary Beth Laughton ..."

In [3]:
df.to_csv('stockdata.csv',index=False)